name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.18.0 <3.0.0'

# Add regular dependencies here.
dependencies:
  shelf_sessions:
    path: ..

  mysql_client: ^0.0.27
  postgresql2: ^1.5.1
  shelf_router: ^1.1.3
  shelf_static: ^1.1.1
  sqlite3: ^2.3.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
