name: example_shelf
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.18.0 <3.0.0'

# Add regular dependencies here.
dependencies:
  example:
    path: ../example
  session_shelf:
    path: ..
  shelf_router: ^1.1.3
  shelf_static: ^1.1.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
